---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: pre-check
    pull: default
    image: rancher/dapper:v0.4.2
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    commands:
      - apk add git make curl go=1.12.12-r0
      - make -f Makefile.pandaria pre-check
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag

  - name: build
    pull: default
    image: rancher/dapper:v0.4.2
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    commands:
      - apk add git make curl go=1.12.12-r0 bzr
      - make -f Makefile.pandaria
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-amd64

trigger:
  event:
    exclude:
      - promote
