---
kind: pipeline
name: default-windows-ltsc2022

platform:
  os: windows
  arch: amd64
  version: 2022

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.5.8
  environment:
    OAUTH_TOKEN:
      from_secret: github_token
    SKIP_TESTS: 1
  commands:
  - dapper.exe -f Dockerfile-windows-pandaria.dapper ci
  privileged: true
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

node:
  instance: agent-win-2022
---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.5.8
  environment:
    OAUTH_TOKEN:
      from_secret: github_token
    SKIP_TESTS: 1
  commands:
  - dapper.exe -f Dockerfile-windows-pandaria.dapper ci
  privileged: true
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

node:
  instance: agent-win-111